# Generated by Django 3.2.3 on 2021-05-24 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bottle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.FloatField(verbose_name='c')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
            ],
        ),
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
            ],
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'verbose_name': 'Task', 'verbose_name_plural': 'Tasks'},
        ),
        migrations.CreateModel(
            name='ComponentLimit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('limit', models.FloatField(verbose_name='b')),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.component')),
            ],
        ),
        migrations.CreateModel(
            name='ComponentCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.FloatField(verbose_name='a')),
                ('bottle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.bottle')),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.component')),
            ],
        ),
    ]
