# Generated by Django 3.2.3 on 2021-05-25 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210524_1615'),
    ]

    operations = [
        migrations.AddField(
            model_name='bottle',
            name='xMax',
            field=models.IntegerField(default=0, verbose_name='xmax'),
        ),
        migrations.AddField(
            model_name='bottle',
            name='xMin',
            field=models.IntegerField(default=0, verbose_name='xmin'),
        ),
        migrations.AddField(
            model_name='component',
            name='q0',
            field=models.FloatField(default=0.0, verbose_name='q'),
        ),
        migrations.AddField(
            model_name='component',
            name='q1',
            field=models.FloatField(default=0.0, verbose_name='^q'),
        ),
        migrations.AddField(
            model_name='component',
            name='vMax',
            field=models.FloatField(default=100.0, verbose_name='vmax'),
        ),
        migrations.AddField(
            model_name='component',
            name='vMin',
            field=models.FloatField(default=0.0, verbose_name='vmin'),
        ),
        migrations.AddField(
            model_name='component',
            name='wMax',
            field=models.FloatField(default=100.0, verbose_name='wmax'),
        ),
        migrations.AddField(
            model_name='component',
            name='wMin',
            field=models.FloatField(default=0.0, verbose_name='wmin'),
        ),
        migrations.AddField(
            model_name='component',
            name='yMax',
            field=models.FloatField(default=100.0, verbose_name='ymax'),
        ),
        migrations.AddField(
            model_name='component',
            name='yMin',
            field=models.FloatField(default=0.0, verbose_name='ymin'),
        ),
    ]
